version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pathuni
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    main: ./cmd/pathuni
    binary: pathuni
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -extldflags=-Wl,--strip-all
    flags: [-trimpath]
    hooks:
      post:
        - cmd: sh -c 'if command -v upx >/dev/null 2>&1; then if [ "{{ .Os }}" = "darwin" ]; then echo "UPX compression for macOS is officially unsupported until further notice. Skipping... {{ .Path }}..."; else upx --best "{{ .Path }}" || echo "UPX compression failed for {{ .Path }}, continuing..."; fi; else echo "UPX not available, skipping compression for {{ .Path }}"; fi'

archives:
  - id: pathuni
    ids: [pathuni] # fixed
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next" # fixed

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# TODO: Submit to official Homebrew repository once ready
# brews:
#   - name: pathuni
#     homepage: https://github.com/pmdci/pathuni
#     description: "Cross-platform PATH management tool for dotfiles"
#     license: GPL-3.0

release:
  github:
    owner: pmdci
    name: pathuni
  draft: false
  prerelease: auto
  mode: replace
