name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Test dry-run functionality
        run: ./bin/pathuni dry-run --config=cmd/pathuni/testdata/platform_specific.yaml --shell=bash
